### PR TITLE
Add support to Scale X

### PR DESCRIPTION
**Pull request by svanhoutte**
Added support to the last Scale, confirmed it works

### CODE REVIEW

**Comment by hank-weber** [comment]
any plans to complete this? I'm trying to use with the Scale X and running into unsupported issues

**Comment by svanhoutte** [comment]
@shauntarves could you merge this change to the main ? Thanks a lot.

**Comment by hank-weber** [comment]
not too concerned anymore as i've made the changes locally but would be nice

**Comment by shauntarves** [comment]
Hey guys, sorry about the delay on this. I started working on it a while ago and just got distracted with other things. Trying to dust off my memory, but I ended up having to make some other associated changes but now I can't remember exactly why.

Either way, if this works for you, @svanhoutte can you just remove the `# placeholder` if that model string is verified to be correct? I can confirm it in the code if you have any doubts, but seems like it would have to be if things are working

**Comment by svanhoutte** [comment]
@shauntarves yes I verified and the string is correct and working. I removed the ` # placeholder ` in the code. you should be able to merge without concerns.

**Pull request merged**
