### PR TITLE
66 support for wyze switch

### PR DESCRIPTION
**Pull request by shauntarves**

### CODE REVIEW

**Comment by jsjax** [comment]
Hey, is there any reason not to land this?  I'm super interested to give it a whirl.  Happy to test as well on my project if not.

**Comment by shauntarves** [comment]
Hey @jsjax,

I'd love to get this released - I was just hoping to have another set of eyes on it before merging, but if it's easier for you to use as part of a release, let me know and I'll just merge it. I don't want to wait any longer than necessary either, but it's always good for another user to confirm I didn't mess something up.

**Comment by jsjax** [comment]
Well, if you want I can pull this over the weekend and try it on my setup.  I won't get to it before Saturday.  It's not that different for me, either way.

**Comment by jsjax** [comment]
:partying_face:

**Pull request merged**
